import type { Request, Response, NextFunction, RequestHandler } from 'express';
import { timingSafeEqual } from 'node:crypto';
import { type DB, type Row, one, run, digest, token, now, verifyPassword, audit } from './db.js';
import { AppError, baseUrl, safeUser } from './domain.js';
declare global {namespace Express {interface Request {user?:Row;session?:Row;tenantId?:string;}}}
export const safeEqual=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);};
export const cookieName='fidelity_session';
const cookieOptions=()=>({httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/api'});
export function requireOrigin(req:Request,_res:Response,next:NextFunction){if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const origin=req.get('origin');if(!origin||origin!==new URL(baseUrl()).origin)return next(new AppError(403,'Origine della richiesta non autorizzata','ORIGIN_MISMATCH'));next();}
export function auth(db:DB):RequestHandler {return (req,_res,next)=>{const raw=req.cookies?.[cookieName];if(typeof raw!=='string')return next(new AppError(401,'Accedi per continuare','UNAUTHENTICATED'));const session=one(db,'SELECT * FROM sessions WHERE token_hash=? AND expires_at>?',digest(raw),now());if(!session)return next(new AppError(401,'Sessione scaduta. Accedi di nuovo.','UNAUTHENTICATED'));const user=one(db,'SELECT * FROM users WHERE id=? AND active=1',session.user_id);if(!user)return next(new AppError(401,'Account non attivo','UNAUTHENTICATED'));req.user=user;req.session=session;if(!['GET','HEAD','OPTIONS'].includes(req.method)&&!safeEqual(req.get('x-csrf-token')||'',session.csrf_token))return next(new AppError(403,'Sessione di sicurezza non valida. Ricarica la pagina.','CSRF_INVALID'));next();};}
export function roles(...allowed:string[]):RequestHandler {return(req,_res,next)=>allowed.includes(req.user?.role)?next():next(new AppError(403,'Non hai i permessi per questa operazione','FORBIDDEN'));}
export function scope(db:DB):RequestHandler{return(req,_res,next)=>{const tenantId=req.user!.role==='agency'?req.get('x-tenant-id'):req.user!.tenant_id;if(!tenantId)return next(new AppError(400,'Seleziona un’attività','TENANT_REQUIRED'));if(!one(db,'SELECT id FROM tenants WHERE id=? AND active=1',tenantId))return next(new AppError(404,'Attività non disponibile','NOT_FOUND'));req.tenantId=tenantId;next();};}
export function login(db:DB,email:string,password:string,req:Request,res:Response){const user=one(db,'SELECT * FROM users WHERE email=? AND active=1',email.toLowerCase());const dummy='b1f213325a9537be63150c1acfcaa1a2:'+ '0'.repeat(128);const valid=verifyPassword(password,user?.password_hash||dummy);if(!user||!valid)throw new AppError(401,'Email o password non corretta','INVALID_CREDENTIALS');if(user.tenant_id&&!one(db,'SELECT id FROM tenants WHERE id=? AND active=1',user.tenant_id))throw new AppError(403,'Attività sospesa');const raw=token(),csrf=token(),time=now();if(req.cookies?.[cookieName])run(db,'DELETE FROM sessions WHERE token_hash=?',digest(req.cookies[cookieName]));run(db,'DELETE FROM sessions WHERE expires_at<=?',time);run(db,'INSERT INTO sessions VALUES(?,?,?,?,?)',digest(raw),user.id,csrf,new Date(Date.now()+12*60*60*1000).toISOString(),time);audit(db,user.tenant_id,user.id,'auth.login',user.id);res.cookie(cookieName,raw,{...cookieOptions(),maxAge:12*60*60*1000});return{user:safeUser(user),csrfToken:csrf};}
export function logout(db:DB,req:Request,res:Response){run(db,'DELETE FROM sessions WHERE token_hash=?',req.session!.token_hash);res.clearCookie(cookieName,cookieOptions());return{ok:true};}
