import { z } from 'zod';
import { type DB, type Row, all, one, run, atomic, id, token, now, sequence, enqueue, audit, digest } from './db.js';

export class AppError extends Error {constructor(public status:number,message:string,public code='BAD_REQUEST'){super(message);}}
export const required = <T>(value:T|undefined|null,message='Elemento non trovato'):T => {if(value==null)throw new AppError(404,message,'NOT_FOUND');return value;};
export const baseUrl=()=> (process.env.PUBLIC_BASE_URL||'http://localhost:5173').replace(/\/$/,'');
export const validName=z.string().trim().min(2).max(120);
export const colorSchema=z.string().regex(/^#[0-9a-fA-F]{6}$/);
export const tenantSchema=z.object({name:validName,slug:z.string().trim().min(3).max(64).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),industry:z.string().trim().max(100).default(''),color:colorSchema.default('#7357ff'),address:z.string().trim().max(250).default('')});
export const programSchema=z.object({name:validName,type:z.enum(['stamps','points','coupon']),description:z.string().trim().max(1000).default(''),rewardThreshold:z.number().int().min(1).max(1000000),rewardName:validName,color:colorSchema.default('#7357ff'),pointsPerEuro:z.number().min(.01).max(1000).default(1),expiresAt:z.iso.datetime().nullable().optional(),locations:z.array(z.object({latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),relevantText:z.string().max(100).optional()})).max(10).default([])});
export const memberSchema=z.object({programId:z.string().uuid(),name:validName,email:z.email().trim().toLowerCase().max(254),phone:z.string().trim().max(30).default(''),marketingConsent:z.boolean().default(false)});
export const operationSchema=z.object({type:z.enum(['credit','redeem']),amount:z.number().int().positive().max(1000000).optional(),spendCents:z.number().int().positive().max(100000000).optional(),note:z.string().trim().max(250).default(''),idempotencyKey:z.string().min(16).max(128)});
export const safeUser=(u:Row)=>({id:u.id,name:u.name,email:u.email,role:u.role,tenantId:u.tenant_id,active:!!u.active});
export const tenantJson=(t:Row)=>({id:t.id,name:t.name,slug:t.slug,industry:t.industry,color:t.color,address:t.address,privacyUrl:t.privacy_url||'',termsText:t.terms_text||'',active:!!t.active,createdAt:t.created_at});
export function programJson(db:DB,p:Row) {const tenant=required(one(db,'SELECT slug FROM tenants WHERE id=?',p.tenant_id));return {id:p.id,tenantId:p.tenant_id,name:p.name,type:p.type,description:p.description,rewardThreshold:p.reward_threshold,rewardName:p.reward_name,color:p.color,pointsPerEuro:p.points_per_euro,active:!!p.active,expiresAt:p.expires_at,locations:JSON.parse(p.locations_json),createdAt:p.created_at,logoUrl:one(db,'SELECT program_id FROM branding WHERE program_id=?',p.id)?`${baseUrl()}/api/branding/${p.id}.png`:null,memberCount:one(db,"SELECT count(*) AS n FROM members WHERE program_id=? AND status='active'",p.id)!.n,joinUrl:`${baseUrl()}/join/${tenant.slug}?program=${p.id}`};}
export function memberJson(db:DB,m:Row) {const p=required(one(db,'SELECT * FROM programs WHERE id=?',m.program_id));return {id:m.id,tenantId:m.tenant_id,programId:m.program_id,programName:p.name,programType:p.type,name:m.name,email:m.email,phone:m.phone,marketingConsent:!!m.marketing_consent,balance:m.balance,totalEarned:m.total_earned,rewardCount:m.reward_count,availableRewards:Math.floor(m.balance/p.reward_threshold),status:m.status,createdAt:m.created_at,updatedAt:m.updated_at,lastVisitAt:m.last_visit_at,cardUrl:m.status==='active'?`${baseUrl()}/card/${m.public_token}`:'',publicToken:m.status==='active'?m.public_token:''};}
export function transactionJson(db:DB,t:Row) {const m=required(one(db,'SELECT name,program_id FROM members WHERE id=?',t.member_id));const p=required(one(db,'SELECT name FROM programs WHERE id=?',m.program_id));return {id:t.id,memberId:t.member_id,memberName:m.name,programName:p.name,type:t.type,amount:t.amount,balanceAfter:t.balance_after,note:t.note,actorName:t.actor_id?one(db,'SELECT name FROM users WHERE id=?',t.actor_id)?.name||'Operatore':'Iscrizione',createdAt:t.created_at,reversed:!!one(db,'SELECT id FROM transactions WHERE reversal_of=?',t.id),reversalOf:t.reversal_of};}
export function campaignJson(db:DB,c:Row) {const counts=all(db,'SELECT status,count(*) AS n FROM campaign_deliveries WHERE campaign_id=? GROUP BY status',c.id);const count=(status:string)=>Number(counts.find(x=>x.status===status)?.n||0);return {id:c.id,name:c.name,title:c.title,body:c.body,segment:c.segment,programId:c.program_id,status:c.status,scheduledAt:c.scheduled_at,createdAt:c.created_at,recipientCount:one(db,'SELECT count(DISTINCT member_id) AS n FROM campaign_deliveries WHERE campaign_id=?',c.id)!.n,sentCount:count('sent'),failedCount:count('failed'),blockedCount:count('blocked')};}
export function activeProgram(db:DB,programId:string,tenantId:string) {const p=required(one(db,'SELECT p.* FROM programs p JOIN tenants t ON t.id=p.tenant_id WHERE p.id=? AND p.tenant_id=? AND t.active=1',programId,tenantId));if(!p.active||(p.expires_at&&p.expires_at<=now()))throw new AppError(409,'Il programma non è attivo o è scaduto','PROGRAM_INACTIVE');return p;}
export function createMember(db:DB,tenantId:string,input:z.infer<typeof memberSchema>,actorId:string|null,source='operator') {return atomic(db,()=>{const p=activeProgram(db,input.programId,tenantId);if(one(db,"SELECT id FROM members WHERE program_id=? AND email=? AND status='active'",p.id,input.email))throw new AppError(409,'Esiste già una tessera per questo indirizzo. Rivolgiti all’attività per recuperarla.','ALREADY_ENROLLED');const memberId=id(),created=now(),balance=p.type==='coupon'?1:0;run(db,`INSERT INTO members(id,tenant_id,program_id,name,email,phone,marketing_consent,consent_at,balance,total_earned,public_token,apple_auth_token,created_at,updated_at,update_seq) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,memberId,tenantId,p.id,input.name,input.email,input.phone,+input.marketingConsent,created,balance,balance,token(),token(),created,created,sequence(db));run(db,'INSERT INTO consent_log VALUES(?,?,?,?,?,?)',id(),memberId,+input.marketingConsent,source,'1',created);if(balance)run(db,'INSERT INTO transactions(id,tenant_id,member_id,type,amount,balance_after,note,actor_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)',id(),tenantId,memberId,'credit',1,1,'Coupon di benvenuto',actorId,created);audit(db,tenantId,actorId,'member.created',memberId);return memberJson(db,required(one(db,'SELECT * FROM members WHERE id=?',memberId)));});}
export function updateConsent(db:DB,m:Row,granted:boolean,source:string) {run(db,'UPDATE members SET marketing_consent=?,consent_at=? WHERE id=?',+granted,now(),m.id);run(db,'INSERT INTO consent_log VALUES(?,?,?,?,?,?)',id(),m.id,+granted,source,'1',now());if(!granted){run(db,"UPDATE campaign_deliveries SET status='blocked',error='Consenso revocato' WHERE member_id=? AND status='pending'",m.id);}}
export function segmentSql(segment:string):string {switch(segment){case'active':return " AND julianday(m.last_visit_at)>=julianday('now','-30 days')";case'inactive':return " AND (julianday(m.last_visit_at)<julianday('now','-30 days') OR (m.last_visit_at IS NULL AND julianday(m.created_at)<julianday('now','-30 days')))";case'reward':return ' AND m.balance>=p.reward_threshold';case'marketing':return ' AND m.marketing_consent=1';default:return '';}}
export function transact(db:DB,tenantId:string,actorId:string,memberId:string,input:z.infer<typeof operationSchema>) {return atomic(db,()=>{const fingerprint=digest(JSON.stringify({actorId,memberId,...input}));const prior=one(db,'SELECT * FROM idempotency WHERE tenant_id=? AND key=?',tenantId,input.idempotencyKey);if(prior){if(prior.fingerprint!==fingerprint)throw new AppError(409,'Chiave di operazione già utilizzata per una richiesta diversa','IDEMPOTENCY_CONFLICT');return JSON.parse(prior.response_json);}
  const m=required(one(db,"SELECT * FROM members WHERE id=? AND tenant_id=? AND status='active'",memberId,tenantId));const p=activeProgram(db,m.program_id,tenantId);let amount:number;
  if(input.type==='credit'){if(p.type==='coupon')throw new AppError(400,'Il coupon è monouso e non può essere ricaricato');if(input.amount!==undefined&&input.spendCents!==undefined)throw new AppError(400,'Indica punti oppure importo speso');if(input.spendCents!==undefined){if(p.type!=='points')throw new AppError(400,'La spesa è prevista solo per i programmi a punti');amount=Math.floor(input.spendCents*p.points_per_euro/100);}else amount=input.amount||1;if(amount<1||amount>1000000||(p.type==='stamps'&&amount>100))throw new AppError(400,'Quantità non valida');}
  else{if(input.amount!==undefined||input.spendCents!==undefined)throw new AppError(400,'Il costo del premio è stabilito dal programma');amount=-p.reward_threshold;}
  const balance=m.balance+amount;if(balance<0)throw new AppError(409,'Saldo insufficiente per questo premio','INSUFFICIENT_BALANCE');if(balance>1000000000)throw new AppError(400,'Saldo massimo superato');const transactionId=id(),created=now();
  run(db,'UPDATE members SET balance=?,total_earned=total_earned+?,reward_count=reward_count+?,last_visit_at=?,updated_at=?,update_seq=? WHERE id=?',balance,Math.max(0,amount),input.type==='redeem'?1:0,created,created,sequence(db),m.id);
  run(db,'INSERT INTO transactions(id,tenant_id,member_id,type,amount,balance_after,note,actor_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)',transactionId,tenantId,m.id,input.type,amount,balance,input.note,actorId,created);
  enqueue(db,tenantId,m.id);audit(db,tenantId,actorId,`transaction.${input.type}`,transactionId);
  const response={member:memberJson(db,required(one(db,'SELECT * FROM members WHERE id=?',m.id))),transaction:transactionJson(db,required(one(db,'SELECT * FROM transactions WHERE id=?',transactionId)))};
  run(db,'INSERT INTO idempotency VALUES(?,?,?,?,?)',tenantId,input.idempotencyKey,fingerprint,JSON.stringify(response),created);return response;
});}
export function reverseTransaction(db:DB,tenantId:string,actorId:string,transactionId:string,input:{note:string,idempotencyKey:string}) {return atomic(db,()=>{const fingerprint=digest(JSON.stringify({actorId,transactionId,...input}));const previous=one(db,'SELECT * FROM idempotency WHERE tenant_id=? AND key=?',tenantId,input.idempotencyKey);if(previous){if(previous.fingerprint!==fingerprint)throw new AppError(409,'Chiave già utilizzata','IDEMPOTENCY_CONFLICT');return JSON.parse(previous.response_json);}
  const t=required(one(db,'SELECT * FROM transactions WHERE id=? AND tenant_id=?',transactionId,tenantId));if(t.type==='reversal'||one(db,'SELECT id FROM transactions WHERE reversal_of=?',t.id))throw new AppError(409,'Operazione già stornata o non stornabile');const m=required(one(db,"SELECT * FROM members WHERE id=? AND tenant_id=? AND status='active'",t.member_id,tenantId));if(m.balance-t.amount<0)throw new AppError(409,'Lo storno renderebbe il saldo negativo');const created=now(),tid=id();
  run(db,'UPDATE members SET balance=balance-?,total_earned=total_earned-?,reward_count=reward_count-?,updated_at=?,update_seq=? WHERE id=?',t.amount,t.type==='credit'?t.amount:0,t.type==='redeem'?1:0,created,sequence(db),m.id);
  run(db,'INSERT INTO transactions(id,tenant_id,member_id,type,amount,balance_after,note,actor_id,reversal_of,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',tid,tenantId,m.id,'reversal',-t.amount,m.balance-t.amount,input.note,actorId,t.id,created);enqueue(db,tenantId,m.id);audit(db,tenantId,actorId,'transaction.reversal',tid);const response={member:memberJson(db,required(one(db,'SELECT * FROM members WHERE id=?',m.id))),transaction:transactionJson(db,required(one(db,'SELECT * FROM transactions WHERE id=?',tid)))};run(db,'INSERT INTO idempotency VALUES(?,?,?,?,?)',tenantId,input.idempotencyKey,fingerprint,JSON.stringify(response),created);return response;});}
export function queueCampaign(db:DB,tenantId:string,campaignId:string,actorId:string|null) {return atomic(db,()=>{const c=required(one(db,'SELECT * FROM campaigns WHERE id=? AND tenant_id=?',campaignId,tenantId));if(!['draft','scheduled'].includes(c.status))throw new AppError(409,'Campagna già inviata');if(c.scheduled_at&&c.scheduled_at>now()){run(db,"UPDATE campaigns SET status='scheduled' WHERE id=?",c.id);return {campaign:campaignJson(db,{...c,status:'scheduled'}),recipients:0};}const members=all(db,`SELECT m.* FROM members m JOIN programs p ON p.id=m.program_id WHERE m.tenant_id=? AND m.status='active' AND m.marketing_consent=1 AND p.active=1 AND (p.expires_at IS NULL OR p.expires_at>?)${c.program_id?' AND m.program_id=?':''}${segmentSql(c.segment)}`,tenantId,now(),...(c.program_id?[c.program_id]:[]));for(const m of members){for(const channel of ['apple','google']){const deliveryId=id();run(db,'INSERT INTO campaign_deliveries(id,campaign_id,member_id,channel) VALUES(?,?,?,?)',deliveryId,c.id,m.id,channel);enqueue(db,tenantId,m.id,'campaign',{campaignId:c.id,deliveryId,channel});}}
run(db,'UPDATE campaigns SET status=? WHERE id=?',members.length?'queued':'complete',c.id);audit(db,tenantId,actorId,'campaign.queued',c.id);return {campaign:campaignJson(db,required(one(db,'SELECT * FROM campaigns WHERE id=?',c.id))),recipients:members.length};});}
