import { Router } from 'express';
import { rateLimit } from 'express-rate-limit';
import { z } from 'zod';
import { type DB, one, all, run, now, atomic, sequence, enqueue } from './db.js';
import { required, memberSchema, createMember, programJson, tenantJson, AppError, updateConsent } from './domain.js';
import { requireOrigin, safeEqual } from './auth.js';
import { buildApplePass, googleSaveUrl, getWalletStatus, walletIconPng } from './wallet/index.js';
import { walletData } from './wallet-data.js';

export function publicRoutes(db:DB){const router=Router();router.use(requireOrigin);router.use(rateLimit({windowMs:60*1000,limit:60,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Troppe richieste, riprova tra un minuto',code:'RATE_LIMITED'}}));
router.get('/join/:slug',(req,res)=>{const tenant=required(one(db,'SELECT * FROM tenants WHERE slug=? AND active=1',String(req.params.slug)));res.json({demo:one(db,"SELECT value FROM metadata WHERE key='demo'")?.value==='true',tenant:tenantJson(tenant),programs:all(db,'SELECT * FROM programs WHERE tenant_id=? AND active=1 AND (expires_at IS NULL OR expires_at>?) ORDER BY created_at',tenant.id,now()).map(p=>programJson(db,p))});});
router.post('/join/:slug',rateLimit({windowMs:60*60*1000,limit:20,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Limite di iscrizioni raggiunto. Riprova più tardi.',code:'RATE_LIMITED'}}),(req,res)=>{const t=required(one(db,'SELECT * FROM tenants WHERE slug=? AND active=1',String(req.params.slug)));if(process.env.NODE_ENV==='production'&&(!t.privacy_url||!t.terms_text))throw new AppError(503,'Le iscrizioni saranno disponibili dopo la pubblicazione dei documenti dell’attività.','POLICIES_REQUIRED');const input=memberSchema.extend({acceptTerms:z.literal(true)}).parse(req.body);const member=createMember(db,t.id,input,null,'public_signup');res.status(201).json({cardUrl:member.cardUrl,token:member.publicToken});});
const getMember=(value:string)=>required(one(db,"SELECT m.* FROM members m JOIN tenants t ON t.id=m.tenant_id WHERE m.public_token=? AND m.status='active' AND t.active=1",value),'Tessera non disponibile');
router.get('/cards/:token',(req,res)=>{const m=getMember(String(req.params.token)),p=required(one(db,'SELECT * FROM programs WHERE id=?',m.program_id)),t=required(one(db,'SELECT * FROM tenants WHERE id=?',m.tenant_id)),wallet=getWalletStatus();res.json({member:{name:m.name,balance:m.balance,rewardCount:m.reward_count,availableRewards:Math.floor(m.balance/p.reward_threshold),status:m.status,createdAt:m.created_at},program:programJson(db,p),tenant:{name:t.name,color:t.color,address:t.address},wallet:{apple:{configured:wallet.apple.configured},google:{configured:wallet.google.configured}},marketingConsent:!!m.marketing_consent,offer:m.offer});});
router.patch('/cards/:token/consent',(req,res)=>{const m=getMember(String(req.params.token)),input=z.object({marketingConsent:z.boolean()}).parse(req.body);atomic(db,()=>updateConsent(db,m,input.marketingConsent,'card_holder'));res.json({ok:true});});
router.get('/cards/:token/apple',async(req,res)=>{const m=getMember(String(req.params.token)),data=walletData(db,m),pass=await buildApplePass(data.member,data.program);run(db,'UPDATE members SET apple_issued=1 WHERE id=?',m.id);res.set({'Content-Type':'application/vnd.apple.pkpass','Content-Disposition':'attachment; filename="fidelity.pkpass"'}).send(pass);});
router.get('/cards/:token/google',async(req,res)=>{const m=getMember(String(req.params.token)),data=walletData(db,m);run(db,'UPDATE members SET google_issued=1 WHERE id=?',m.id);res.json({url:await googleSaveUrl(data.member,data.program)});});return router;}

export function appleRoutes(db:DB){const router=Router();router.use(rateLimit({windowMs:60000,limit:300,standardHeaders:'draft-8',legacyHeaders:false}));
const validType=(p:string)=>{if(!process.env.APPLE_PASS_TYPE_ID||p!==process.env.APPLE_PASS_TYPE_ID)throw new AppError(404,'Tipo carta non trovato');};
const authenticate=(serial:string,passType:string,authorization:string|undefined)=>{validType(passType);const m=required(one(db,"SELECT m.* FROM members m JOIN tenants t ON t.id=m.tenant_id WHERE m.id=?",serial));if(!safeEqual(authorization||'',`ApplePass ${m.apple_auth_token}`))throw new AppError(401,'Autorizzazione pass non valida');return m;};
router.post('/v1/devices/:device/registrations/:passType/:serial',(req,res)=>{const m=authenticate(String(req.params.serial),String(req.params.passType),req.get('authorization'));const device=z.string().min(8).max(256).parse(req.params.device),body=z.object({pushToken:z.string().min(8).max(256)}).parse(req.body);const exists=one(db,'SELECT 1 FROM apple_registrations WHERE device_id=? AND member_id=?',device,m.id);run(db,'INSERT INTO apple_registrations(device_id,member_id,push_token,created_at) VALUES(?,?,?,?) ON CONFLICT(device_id,member_id) DO UPDATE SET push_token=excluded.push_token',device,m.id,body.pushToken,now());res.status(exists?200:201).end();});
router.delete('/v1/devices/:device/registrations/:passType/:serial',(req,res)=>{const m=authenticate(String(req.params.serial),String(req.params.passType),req.get('authorization'));run(db,'DELETE FROM apple_registrations WHERE device_id=? AND member_id=?',String(req.params.device),m.id);res.status(200).end();});
router.get('/v1/devices/:device/registrations/:passType',(req,res)=>{validType(String(req.params.passType));const since=Number(req.query.passesUpdatedSince||0);if(!Number.isSafeInteger(since)||since<0)throw new AppError(400,'Versione non valida');const rows=all(db,"SELECT m.id,m.update_seq FROM members m JOIN apple_registrations r ON r.member_id=m.id JOIN tenants t ON t.id=m.tenant_id WHERE r.device_id=? AND m.update_seq>?",String(req.params.device),since);if(!rows.length){res.status(204).end();return;}res.json({serialNumbers:rows.map(x=>x.id),lastUpdated:String(Math.max(...rows.map(x=>x.update_seq)))});});
router.get('/v1/passes/:passType/:serial',async(req,res)=>{const m=authenticate(String(req.params.serial),String(req.params.passType),req.get('authorization')),data=walletData(db,m);res.set({'Content-Type':'application/vnd.apple.pkpass','Last-Modified':new Date(m.updated_at).toUTCString(),'Content-Disposition':'attachment; filename="fidelity.pkpass"'}).send(await buildApplePass(data.member,data.program));});
router.post('/v1/log',(req,res)=>{z.object({logs:z.array(z.string().max(1000)).max(20)}).parse(req.body);res.status(200).end();});return router;}
export const iconPng=()=>walletIconPng();
