import { Router } from 'express';
import { z } from 'zod';
import { type DB, one, all, run, id, token, now, atomic, audit, sequence, enqueue, passwordHash, verifyPassword } from './db.js';
import { AppError, required, baseUrl, tenantSchema, programSchema, memberSchema, operationSchema, safeUser, tenantJson, programJson, memberJson, transactionJson, campaignJson, createMember, segmentSql, transact, reverseTransaction, updateConsent, queueCampaign } from './domain.js';
import { auth, roles, scope, logout } from './auth.js';
import { automationJson, runAutomation } from './automations.js';
import { brandingRoutes } from './branding.js';
import { getWalletStatus } from './wallet/index.js';

function present<T extends Record<string,unknown>>(input:T,body:Record<string,unknown>):T {return Object.fromEntries(Object.entries(input).filter(([key])=>Object.hasOwn(body,key))) as T;}

export function privateRoutes(db:DB){const router=Router();router.use(auth(db));const managers=roles('agency','owner');
router.get('/auth/me',(req,res)=>res.json({user:safeUser(req.user!),csrfToken:req.session!.csrf_token}));
router.post('/auth/logout',(req,res)=>res.json(logout(db,req,res)));
router.post('/auth/password',(req,res)=>{const input=z.object({currentPassword:z.string().max(256),newPassword:z.string().min(12).max(128)}).parse(req.body);if(!verifyPassword(input.currentPassword,req.user!.password_hash))throw new AppError(403,'La password attuale non è corretta');atomic(db,()=>{run(db,'UPDATE users SET password_hash=? WHERE id=?',passwordHash(input.newPassword),req.user!.id);run(db,'DELETE FROM sessions WHERE user_id=? AND token_hash!=?',req.user!.id,req.session!.token_hash);audit(db,req.user!.tenant_id,req.user!.id,'auth.password_changed',req.user!.id);});res.json({ok:true});});
router.get('/tenants',(req,res)=>res.json({items:all(db,req.user!.role==='agency'?'SELECT * FROM tenants ORDER BY created_at':'SELECT * FROM tenants WHERE id=?',...(req.user!.role==='agency'?[]:[req.user!.tenant_id])).map(tenantJson)}));
router.post('/tenants',roles('agency'),(req,res)=>{const input=tenantSchema.parse(req.body),tenantId=id();atomic(db,()=>{run(db,'INSERT INTO tenants(id,name,slug,industry,color,address,created_at) VALUES(?,?,?,?,?,?,?)',tenantId,input.name,input.slug,input.industry,input.color,input.address,now());audit(db,tenantId,req.user!.id,'tenant.created',tenantId);});res.status(201).json(tenantJson(required(one(db,'SELECT * FROM tenants WHERE id=?',tenantId))));});
router.patch('/tenants/:id',roles('agency'),(req,res)=>{const old=required(one(db,'SELECT * FROM tenants WHERE id=?',String(req.params.id))),input=present(tenantSchema.partial().extend({active:z.boolean().optional()}).parse(req.body),req.body);atomic(db,()=>{run(db,'UPDATE tenants SET name=?,slug=?,industry=?,color=?,address=?,active=? WHERE id=?',input.name??old.name,input.slug??old.slug,input.industry??old.industry,input.color??old.color,input.address??old.address,input.active===undefined?old.active:+input.active,old.id);
  if((input.name!==undefined&&input.name!==old.name)||(input.active!==undefined&&+input.active!==old.active)){
    for(const m of all(db,"SELECT id FROM members WHERE tenant_id=? AND status='active'",old.id)){
      run(db,'UPDATE members SET updated_at=?,update_seq=? WHERE id=?',now(),sequence(db),m.id);
      enqueue(db,old.id,m.id);
    }
  }
  audit(db,old.id,req.user!.id,'tenant.updated',old.id);});res.json(tenantJson(required(one(db,'SELECT * FROM tenants WHERE id=?',old.id))));});
router.use(scope(db));
router.use(brandingRoutes(db));
router.get('/dashboard',(req,res)=>{const t=req.tenantId!,count=(sql:string)=>Number(one(db,sql,t)!.n);const metrics={members:count("SELECT count(*) n FROM members WHERE tenant_id=? AND status='active'"),activeMembers:count("SELECT count(*) n FROM members WHERE tenant_id=? AND status='active' AND julianday(last_visit_at)>=julianday('now','-30 days')"),credits:count("SELECT coalesce(sum(amount),0) n FROM transactions WHERE tenant_id=? AND type='credit'"),redemptions:count("SELECT count(*) n FROM transactions x WHERE tenant_id=? AND type='redeem' AND NOT EXISTS(SELECT 1 FROM transactions y WHERE y.reversal_of=x.id)"),programs:count('SELECT count(*) n FROM programs WHERE tenant_id=? AND active=1'),marketingMembers:count("SELECT count(*) n FROM members WHERE tenant_id=? AND status='active' AND marketing_consent=1")};const trend=[];for(let i=13;i>=0;i--){const date=new Date(Date.now()-i*86400000).toISOString().slice(0,10),x=one(db,"SELECT coalesce(sum(CASE WHEN type='credit' THEN amount ELSE 0 END),0) credits,sum(CASE WHEN type='redeem' THEN 1 ELSE 0 END) redemptions FROM transactions WHERE tenant_id=? AND substr(created_at,1,10)=?",t,date)!;trend.push({date,credits:x.credits,redemptions:x.redemptions||0,registrations:one(db,"SELECT count(*) n FROM members WHERE tenant_id=? AND substr(created_at,1,10)=?",t,date)!.n});}res.json({metrics,trend,activity:all(db,'SELECT * FROM transactions WHERE tenant_id=? ORDER BY created_at DESC LIMIT 8',t).map(x=>transactionJson(db,x)),programs:all(db,'SELECT * FROM programs WHERE tenant_id=? ORDER BY created_at',t).map(x=>programJson(db,x))});});
router.get('/programs',(req,res)=>res.json({items:all(db,'SELECT * FROM programs WHERE tenant_id=? ORDER BY created_at',req.tenantId).map(p=>programJson(db,p))}));
router.post('/programs',managers,(req,res)=>{const input=programSchema.parse(req.body);if(input.type==='coupon')input.rewardThreshold=1;const pid=id();atomic(db,()=>{run(db,'INSERT INTO programs(id,tenant_id,name,type,description,reward_threshold,reward_name,color,points_per_euro,expires_at,locations_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',pid,req.tenantId,input.name,input.type,input.description,input.rewardThreshold,input.rewardName,input.color,input.pointsPerEuro,input.expiresAt||null,JSON.stringify(input.locations),now());audit(db,req.tenantId!,req.user!.id,'program.created',pid);});res.status(201).json(programJson(db,required(one(db,'SELECT * FROM programs WHERE id=?',pid))));});
router.patch('/programs/:id',managers,(req,res)=>{const p=required(one(db,'SELECT * FROM programs WHERE id=? AND tenant_id=?',String(req.params.id),req.tenantId));const input=present(programSchema.partial().extend({active:z.boolean().optional()}).parse(req.body),req.body);if(input.type&&input.type!==p.type)throw new AppError(409,'Il tipo di programma non può essere modificato');if(input.rewardThreshold&&input.rewardThreshold!==p.reward_threshold&&one(db,'SELECT id FROM members WHERE program_id=? LIMIT 1',p.id))throw new AppError(409,'La soglia non può cambiare dopo la prima iscrizione');if(p.type==='coupon'&&input.rewardThreshold&&input.rewardThreshold!==1)throw new AppError(400,'Il coupon è monouso');atomic(db,()=>{run(db,'UPDATE programs SET name=?,description=?,reward_threshold=?,reward_name=?,color=?,points_per_euro=?,active=?,expires_at=?,locations_json=? WHERE id=?',input.name??p.name,input.description??p.description,input.rewardThreshold??p.reward_threshold,input.rewardName??p.reward_name,input.color??p.color,input.pointsPerEuro??p.points_per_euro,input.active===undefined?p.active:+input.active,input.expiresAt===undefined?p.expires_at:input.expiresAt,input.locations?JSON.stringify(input.locations):p.locations_json,p.id);for(const m of all(db,"SELECT id FROM members WHERE program_id=? AND status='active'",p.id)){run(db,'UPDATE members SET updated_at=?,update_seq=? WHERE id=?',now(),sequence(db),m.id);enqueue(db,req.tenantId!,m.id);}audit(db,req.tenantId!,req.user!.id,'program.updated',p.id);});res.json(programJson(db,required(one(db,'SELECT * FROM programs WHERE id=?',p.id))));});
router.get('/members/export',managers,(req,res)=>{const rows=all(db,"SELECT name,email,phone,balance,marketing_consent,created_at FROM members WHERE tenant_id=? AND status='active' ORDER BY name",req.tenantId);const cell=(v:any)=>'"'+String(v??'').replace(/^[=+\-@\t\r]/,"'$&").replace(/"/g,'""')+'"';res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="clienti.csv"','Cache-Control':'no-store'}).send('\uFEFF'+[['Nome','Email','Telefono','Saldo','Consenso marketing','Iscrizione'],...rows.map(r=>Object.values(r))].map(r=>r.map(cell).join(',')).join('\r\n'));audit(db,req.tenantId!,req.user!.id,'members.export','all');});
router.get('/members',(req,res)=>{const q=String(req.query.q||'').slice(0,100),program=String(req.query.programId||''),segment=String(req.query.segment||'all');const rows=all(db,`SELECT m.* FROM members m JOIN programs p ON p.id=m.program_id WHERE m.tenant_id=? AND m.status='active'${q?" AND (m.name LIKE ? ESCAPE '\\' OR m.email LIKE ? ESCAPE '\\')":''}${program?' AND m.program_id=?':''}${segmentSql(segment)} ORDER BY m.created_at DESC LIMIT 1000`,req.tenantId,...(q?Array(2).fill('%'+q.replace(/[\\%_]/g,'\\$&')+'%'):[]),...(program?[program]:[]));res.json({items:rows.map(m=>memberJson(db,m))});});
router.post('/members',managers,(req,res)=>res.status(201).json(createMember(db,req.tenantId!,memberSchema.parse(req.body),req.user!.id)));
const memberDetail=(memberId:string,tenantId:string)=>{const m=required(one(db,"SELECT * FROM members WHERE id=? AND tenant_id=? AND status='active'",memberId,tenantId));return{member:memberJson(db,m),transactions:all(db,'SELECT * FROM transactions WHERE member_id=? ORDER BY created_at DESC LIMIT 100',m.id).map(t=>transactionJson(db,t))};};
router.get('/members/:id',(req,res)=>res.json(memberDetail(String(req.params.id),req.tenantId!)));
router.patch('/members/:id',managers,(req,res)=>{const m=required(one(db,"SELECT * FROM members WHERE id=? AND tenant_id=? AND status='active'",String(req.params.id),req.tenantId));const input=present(memberSchema.omit({programId:true}).partial().parse(req.body),req.body);atomic(db,()=>{run(db,'UPDATE members SET name=?,email=?,phone=?,updated_at=?,update_seq=? WHERE id=?',input.name??m.name,input.email??m.email,input.phone??m.phone,now(),sequence(db),m.id);if(input.marketingConsent!==undefined&&input.marketingConsent!==!!m.marketing_consent)updateConsent(db,m,input.marketingConsent,'operator');enqueue(db,req.tenantId!,m.id);audit(db,req.tenantId!,req.user!.id,'member.updated',m.id);});res.json(memberJson(db,required(one(db,'SELECT * FROM members WHERE id=?',m.id))));});
router.delete('/members/:id',managers,(req,res)=>{const m=required(one(db,"SELECT * FROM members WHERE id=? AND tenant_id=? AND status='active'",String(req.params.id),req.tenantId));atomic(db,()=>{run(db,"UPDATE members SET name='Cliente cancellato',email=?,phone='',marketing_consent=0,status='deleted',public_token=?,offer=NULL,updated_at=?,update_seq=? WHERE id=?",`deleted-${id()}@invalid`,token(),now(),sequence(db),m.id);run(db,'DELETE FROM consent_log WHERE member_id=?',m.id);run(db,'DELETE FROM google_notifications WHERE member_id=?',m.id);run(db,"UPDATE transactions SET note='' WHERE member_id=?",m.id);run(db,"UPDATE jobs SET status='blocked',payload_json='{}',error='Cliente cancellato' WHERE member_id=?",m.id);run(db,"UPDATE campaign_deliveries SET status='blocked',error='Cliente cancellato' WHERE member_id=?",m.id);run(db,'DELETE FROM idempotency WHERE tenant_id=? AND response_json LIKE ?',req.tenantId,`%${m.id}%`);run(db,'DELETE FROM automation_runs WHERE member_id=?',m.id);enqueue(db,req.tenantId!,m.id,'wallet_revoke');audit(db,req.tenantId!,req.user!.id,'member.deleted',m.id);});res.json({ok:true});});
router.post('/scan',(req,res)=>{let code=z.object({code:z.string().trim().min(8).max(2048)}).parse(req.body).code;if(code.startsWith('http')){try{const url=new URL(code);if(url.origin!==new URL(baseUrl()).origin||!url.pathname.startsWith('/card/'))throw new Error();code=decodeURIComponent(url.pathname.slice(6));}catch{throw new AppError(400,'QR non riconosciuto');}}const m=required(one(db,"SELECT id FROM members WHERE tenant_id=? AND status='active' AND (public_token=? OR id=?)",req.tenantId,code,code),'Tessera non trovata per questa attività');res.json(memberDetail(m.id,req.tenantId!));});
router.post('/members/:id/transactions',(req,res)=>res.status(201).json(transact(db,req.tenantId!,req.user!.id,String(req.params.id),operationSchema.parse(req.body))));
router.post('/transactions/:id/reverse',managers,(req,res)=>res.json(reverseTransaction(db,req.tenantId!,req.user!.id,String(req.params.id),z.object({note:z.string().trim().min(3).max(250),idempotencyKey:z.string().min(16).max(128)}).parse(req.body))));
router.get('/transactions',(req,res)=>res.json({items:all(db,'SELECT * FROM transactions WHERE tenant_id=? ORDER BY created_at DESC LIMIT 200',req.tenantId).map(t=>transactionJson(db,t))}));
router.get('/campaigns',managers,(req,res)=>res.json({items:all(db,'SELECT * FROM campaigns WHERE tenant_id=? ORDER BY created_at DESC',req.tenantId).map(c=>campaignJson(db,c))}));
router.post('/campaigns',managers,(req,res)=>{const input=z.object({name:z.string().trim().min(2).max(120),title:z.string().trim().min(2).max(60),body:z.string().trim().min(3).max(500),segment:z.enum(['all','active','inactive','reward']),programId:z.string().uuid().optional(),scheduledAt:z.iso.datetime().optional()}).parse(req.body);if(input.programId)required(one(db,'SELECT id FROM programs WHERE id=? AND tenant_id=?',input.programId,req.tenantId));const cid=id();run(db,'INSERT INTO campaigns(id,tenant_id,name,title,body,segment,program_id,scheduled_at,created_at) VALUES(?,?,?,?,?,?,?,?,?)',cid,req.tenantId,input.name,input.title,input.body,input.segment,input.programId||null,input.scheduledAt||null,now());audit(db,req.tenantId!,req.user!.id,'campaign.created',cid);res.status(201).json(campaignJson(db,required(one(db,'SELECT * FROM campaigns WHERE id=?',cid))));});
router.post('/campaigns/:id/send',managers,(req,res)=>res.json(queueCampaign(db,req.tenantId!,String(req.params.id),req.user!.id)));
router.get('/campaigns/:id',managers,(req,res)=>{const c=required(one(db,'SELECT * FROM campaigns WHERE id=? AND tenant_id=?',String(req.params.id),req.tenantId));res.json({campaign:campaignJson(db,c),deliveries:all(db,'SELECT d.*,m.name FROM campaign_deliveries d JOIN members m ON m.id=d.member_id WHERE d.campaign_id=?',c.id).map(d=>({id:d.id,memberName:d.name,channel:d.channel,status:d.status,error:d.error}))});});
router.get('/settings',(req,res)=>{const counts=all(db,'SELECT status,count(*) n FROM jobs WHERE tenant_id=? GROUP BY status',req.tenantId);res.json({tenant:tenantJson(required(one(db,'SELECT * FROM tenants WHERE id=?',req.tenantId))),wallet:getWalletStatus(),jobs:{pending:counts.find(x=>x.status==='pending')?.n||0,failed:counts.find(x=>x.status==='failed')?.n||0,blocked:counts.find(x=>x.status==='blocked')?.n||0},publicBaseUrl:baseUrl(),demo:one(db,"SELECT value FROM metadata WHERE key='demo'")?.value==='true'});});
router.get('/users',managers,(req,res)=>res.json({items:all(db,'SELECT * FROM users WHERE tenant_id=? ORDER BY created_at',req.tenantId).map(safeUser)}));
router.post('/users',managers,(req,res)=>{const input=z.object({name:z.string().trim().min(2).max(100),email:z.email().toLowerCase().max(254),password:z.string().min(12).max(128),role:z.enum(['owner','staff'])}).parse(req.body);const uid=id();run(db,'INSERT INTO users(id,tenant_id,name,email,password_hash,role,created_at) VALUES(?,?,?,?,?,?,?)',uid,req.tenantId,input.name,input.email,passwordHash(input.password),input.role,now());audit(db,req.tenantId!,req.user!.id,'user.created',uid);res.status(201).json(safeUser(required(one(db,'SELECT * FROM users WHERE id=?',uid))));});
router.patch('/users/:id',managers,(req,res)=>{const u=required(one(db,'SELECT * FROM users WHERE id=? AND tenant_id=?',String(req.params.id),req.tenantId));const input=z.object({name:z.string().trim().min(2).max(100).optional(),role:z.enum(['owner','staff']).optional(),active:z.boolean().optional()}).parse(req.body);if(u.id===req.user!.id&&(input.active===false||input.role==='staff'))throw new AppError(400,'Non puoi revocare il tuo accesso');if(u.role==='owner'&&(input.active===false||input.role==='staff')&&one(db,"SELECT count(*) n FROM users WHERE tenant_id=? AND role='owner' AND active=1",req.tenantId)!.n<2)throw new AppError(409,'Mantieni almeno un titolare attivo');run(db,'UPDATE users SET name=?,role=?,active=? WHERE id=?',input.name??u.name,input.role??u.role,input.active===undefined?u.active:+input.active,u.id);if(input.active===false||input.role)run(db,'DELETE FROM sessions WHERE user_id=?',u.id);audit(db,req.tenantId!,req.user!.id,'user.updated',u.id);res.json(safeUser(required(one(db,'SELECT * FROM users WHERE id=?',u.id))));});
router.get('/audit',managers,(req,res)=>res.json({items:all(db,'SELECT a.*,u.name FROM audit a LEFT JOIN users u ON u.id=a.actor_id WHERE a.tenant_id=? ORDER BY a.created_at DESC LIMIT 200',req.tenantId).map(a=>({id:a.id,actorName:a.name||'Sistema',action:a.action,entityId:a.entity_id,createdAt:a.created_at}))}));
router.post('/jobs/retry',managers,(req,res)=>{const result=run(db,"UPDATE jobs SET status='pending',attempts=0,error=NULL,available_at=? WHERE tenant_id=? AND status IN('blocked','failed') AND (type='wallet_revoke' OR member_id IN(SELECT id FROM members WHERE status='active')) AND coalesce(error,'') NOT LIKE 'Esito Google incerto%'",now(),req.tenantId);run(db,"UPDATE campaign_deliveries SET status='pending',error=NULL WHERE id IN(SELECT json_extract(payload_json,'$.deliveryId') FROM jobs WHERE tenant_id=? AND status='pending' AND type='campaign') AND member_id IN(SELECT id FROM members WHERE status='active' AND marketing_consent=1)",req.tenantId);run(db,"UPDATE campaigns SET status='queued' WHERE tenant_id=? AND status='complete' AND EXISTS(SELECT 1 FROM campaign_deliveries d WHERE d.campaign_id=campaigns.id AND d.status='pending')",req.tenantId);res.json({requeued:result.changes});});
router.get('/automations',managers,(req,res)=>res.json({items:all(db,'SELECT * FROM automations WHERE tenant_id=? ORDER BY created_at DESC',req.tenantId).map(automationJson)}));
router.post('/automations',managers,(req,res)=>{const input=z.object({name:z.string().trim().min(2).max(120),title:z.string().trim().min(2).max(60),body:z.string().trim().min(3).max(500),inactiveDays:z.number().int().min(7).max(365),cooldownDays:z.number().int().min(7).max(365),programId:z.string().uuid().optional()}).parse(req.body);if(input.programId)required(one(db,'SELECT id FROM programs WHERE id=? AND tenant_id=?',input.programId,req.tenantId));const aid=id();run(db,'INSERT INTO automations(id,tenant_id,name,title,body,inactive_days,cooldown_days,program_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)',aid,req.tenantId,input.name,input.title,input.body,input.inactiveDays,input.cooldownDays,input.programId||null,now());audit(db,req.tenantId!,req.user!.id,'automation.created',aid);res.status(201).json(automationJson(required(one(db,'SELECT * FROM automations WHERE id=?',aid))));});
router.patch('/automations/:id',managers,(req,res)=>{const a=required(one(db,'SELECT * FROM automations WHERE id=? AND tenant_id=?',String(req.params.id),req.tenantId)),input=z.object({active:z.boolean()}).parse(req.body);run(db,'UPDATE automations SET active=? WHERE id=?',+input.active,a.id);res.json(automationJson(required(one(db,'SELECT * FROM automations WHERE id=?',a.id))));});
router.post('/automations/:id/run',managers,(req,res)=>res.json(runAutomation(db,req.tenantId!,String(req.params.id),req.user!.id)));
router.patch('/settings/policies',managers,(req,res)=>{const input=z.object({privacyUrl:z.union([z.literal(''),z.url().refine(v=>new URL(v).protocol==='https:','Usa un URL HTTPS')]),termsText:z.string().trim().max(10000)}).parse(req.body);run(db,'UPDATE tenants SET privacy_url=?,terms_text=? WHERE id=?',input.privacyUrl,input.termsText,req.tenantId);audit(db,req.tenantId!,req.user!.id,'tenant.policies_updated',req.tenantId!);res.json({ok:true});});
return router;}
